# Dockerfile.test - VERSÃO CORRIGIDA E COMPLETA

# Imagem base com Python 3.9
FROM python:3.9-slim-buster

# Define o diretório de trabalho para /app
WORKDIR /app

ENV PYTHONPATH=/app

# Copia o arquivo de requisitos primeiro (bom para o cache do Docker)
COPY requirements.txt .

# Instala as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

# Copia os testes para dentro da imagem
COPY ./tests ./tests

CMD ["pytest"]